### PR TITLE
[refactor] Use `when` and `unless` instead of `if` when possible

### PR DESCRIPTION
**Pull request by aru-hackZ**
Just some minor refactor for better readability.

Use `when` when there is no else part in an `if`.

When the above is applied, use `unless` if you have a `(when (not cond) (stuff))` which would look `(unless cond (stuff))`.

Also removing unnecessary `if` and aligning the else part of an `if`.

### CODE REVIEW

**Comment by rougier** [comment]
Thanks. Could you sign the [Emacs Copyright assignment](https://www.gnu.org/software/emacs/manual/html_node/emacs/Copyright-Assignment.html) such that I can merge your fix (after rebase)?

**Comment by aru-hackZ** [comment]
First time doing this, so I have to send a mail to emacs-devel@gnu.org to sign it or how?

**Comment by rougier** [comment]
Yes, see for example here: https://lists.gnu.org/archive/html/emacs-devel/2021-12/msg00806.html

**Comment by aru-hackZ** [comment]
Forgot to update you, I sent the signed pdf form like 2 weeks ago (it took some time to get the response), yet still waiting for them to sign it too.

**Comment by rougier** [comment]
Any news since? Also, you 'll need to rebase your PR I think.

**Comment by aru-hackZ** [comment]
"Nicolas P. Rougier" ***@***.***> writes:

> Any news since? Also, you 'll need to rebase your PR I think.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.

Still no news ...
When the process finishes I will do the rebase

-- 
Alberto (a.k.a. aru)

**Comment by rougier** [comment]
Still no news ? That's quite an unusual long time. You may have to ask again.

**Comment by rougier** [comment]
Sorry, wrong button.

**Comment by aru-hackZ** [comment]
Yep, no news, I will send the email again.

**Comment by aru-hackZ** [comment]
There it goes.

**Comment by rougier** [comment]
At last! Thanks!

**Pull request merged**
